// Class for controlling the direction of rover.

#ifndef DIRECTION_H
#define DIRECTION_H


enum DIR{ N, E, S, W} ;


class Direction{
public:
    Direction(DIR);
    void updateDirection(int);
    DIR getDirection();


private:
    DIR direction; 

};


/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 
/* IMPLEMENTION BELOW BECAUSE TOO LAZY TO CREATE .CPP FILE FOR EACH HEADER */ 




Direction::Direction(DIR d){
    updateDirection(d);
}

void Direction::updateDirection(int d){
    direction = (DIR)d;
};

DIR Direction::getDirection(){
    return direction;
};

#endif